name: Deploy frontend application
'on':
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: dto80/234-deploylab-frontend:latest
      -
        name: run docker compose
        uses: astappiev/docker-compose-remote-action@master
        with:
          ssh_host: ${{ secrets.HOST_SERVER }}
          ssh_user: ${{ secrets.HOST_USER_NAME }}
          ssh_private_key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          ssh_host_public_key : ${{ secrets.HOST_SSH_PUBLIC_KEY }}
          docker_compose_prefix: frontend
